#!/bin/sh
#
# Copyright (C) 2013-2015 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

PHP_FPM_POOL_DIR=/etc/php5/fpm/pool.d
OMV_WEBDAV_POOL_CONF="${PHP_FPM_POOL_DIR}/openmediavault-webdav.conf"
OMV_WEBDAV_XPATH="/config/services/webdav"

if [ -e "${OMV_WEBDAV_POOL_CONF}" ]; then
    rm ${OMV_WEBDAV_POOL_CONF}
fi

if [ "$(omv_config_get "${OMV_WEBDAV_XPATH}/enable")" != "1" ]; then
    exit 0
fi

upload_max=$(omv_config_get "${OMV_WEBDAV_XPATH}/upload_max")

cat > "${OMV_WEBDAV_POOL_CONF}" <<EOF
[openmediavault-webdav]
listen = /var/run/php5-fpm-openmediavault-webdav.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0600

user = www-data
group = www-data

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

php_value[include_path] = ".:/usr/share/php"
php_value[date.timezone] = UTC
php_value[expose_php] = Off
php_value[post_max_size] = ${upload_max}M
php_value[session.name] = OMVWEBDAVSESSID
php_value[upload_max_filesize] = ${upload_max}M
php_flag[always_populate_raw_post_data] = Off
php_flag[magic_quotes_gpc] = Off
php_flag[mbstring.func_overload] = Off
php_flag[output_buffering] = Off
EOF

exit 0
