#!/bin/sh
#
# Copyright (C) 2013-2015 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_WEBDAV_DOCUMENTROOT_DIR="/var/www/webdav/public"
OMV_WEBDAV_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-webdav.conf"

if [ -e "${OMV_WEBDAV_SITE_CONF}" ]; then
    rm ${OMV_WEBDAV_SITE_CONF}
fi

if [ "$(omv_config_get "/config/services/webdav/enable")" != "1" ]; then
    exit 0
fi

cat <<EOF > "${OMV_WEBDAV_SITE_CONF}"
location /webdav {
    alias ${OMV_WEBDAV_DOCUMENTROOT_DIR};

    rewrite ^/webdav/(.*)$ /webdav/index.php last;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm-openmediavault-webdav.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }
}
EOF

exit 0
