#!/bin/sh
#
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# References:
# http://wiki.nginx.org/WordPress
# http://codex.wordpress.org/Nginx

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

WEBDAV_PROXY_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-webdav.conf"
WEBDAV_AVAILABLE_CONF="/etc/nginx/sites-available/openmediavault-webdav.conf"
WEBDAV_ENABLED_DIR="/etc/nginx/sites-enabled/"
WEBDAV_ENABLED_CONF="${WEBDAV_ENABLED_DIR}openmediavault-webdav.conf"

if [ -e "${WEBDAV_ENABLED_CONF}" ]; then
    rm ${WEBDAV_PROXY_CONF}
    rm ${WEBDAV_ENABLED_CONF}
fi

if [ "$(omv_config_get "//services/webdav/enable")" != "1" ]; then
    exit 0
fi

cat <<EOF > "${WEBDAV_PROXY_CONF}"
location /webdav/ {
    return 301 http://\$host:90;
}
EOF

sfref=$(omv_config_get "//services/webdav/sharedfolderref")
sfpath=$(omv_get_sharedfolder_path "${sfref}")

cat <<EOF > "${WEBDAV_AVAILABLE_CONF}"
server {
    listen 90 default_server;

    location / {
        root ${sfpath};

        client_body_temp_path /tmp/webdav-client-tmp 1 2;
        create_full_put_path on;
        client_max_body_size 2g;

        dav_access user:rw group:rw all:r;
        dav_methods PUT DELETE MKCOL COPY MOVE;
        dav_ext_methods PROPFIND OPTIONS;
    }

    large_client_header_buffers 4 32k;
}
EOF

ln -s ${WEBDAV_AVAILABLE_CONF} ${WEBDAV_ENABLED_DIR}

chown -R www-data:users "${sfpath}"
#setfacl -R -m g:webdavusers:rw "${sfpath}"
#setfacl -R -m u:www-data:rw "${sfpath}"

exit 0
