#!/bin/sh
#
# Copyright (C) 2013-2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_WEBDAV_SERVER_CONF="/var/www/webdav/config/config.php"
OMV_WEBDAV_XPATH="/config/services/webdav"

if [ "$(omv_config_get "${OMV_WEBDAV_XPATH}/enable")" != "1" ]; then
    exit 0
fi

sharedfolderref=$(omv_config_get "${OMV_WEBDAV_XPATH}/sharedfolderref")
share_path=$(omv_get_sharedfolder_path "${sharedfolderref}")

cat > "${OMV_WEBDAV_SERVER_CONF}" <<EOF
<?php

\$publicDir = "${share_path}";
EOF
