#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

WEBDAV_PROXY_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-webdav.conf"
WEBDAV_AVAILABLE_CONF="/etc/nginx/sites-available/openmediavault-webdav.conf"
WEBDAV_ENABLED_DIR="/etc/nginx/sites-enabled/"
WEBDAV_ENABLED_CONF="${WEBDAV_ENABLED_DIR}openmediavault-webdav.conf"

case "$1" in

    purge)
        # Remove the configuration data
        omv_config_delete "/config/services/webdav"
    ;;

    remove)

        if [ -f ${WEBDAV_PROXY_CONF} ]; then
            rm -f ${WEBDAV_PROXY_CONF}
        fi

        if [ -f ${WEBDAV_ENABLED_CONF} ]; then
            rm -f ${WEBDAV_ENABLED_CONF}
        fi

        if [ -f ${WEBDAV_AVAILABLE_CONF} ]; then
            rm -f ${WEBDAV_AVAILABLE_CONF}
        fi

        service nginx reload
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
