#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in

    purge)
        # Remove the configuration data
        omv_config_delete "/config/services/webdav"
    ;;

    remove)

        if [ -f /etc/apache2/sites-enabled/omv-webdav ]
            then
                rm -f /etc/apache2/sites-enabled/omv-webdav
        fi

        if [ -f /etc/apache2/sites-available/omv-webdav ]
            then
                rm -f /etc/apache2/sites-available/omv-webdav
        fi

        if [ -h /etc/apache2/mods-enabled/dav_fs.load ]
            then
                a2dismod dav_fs 2>&1
                a2dismod dav 2>&1
        fi

        /etc/init.d/apache2 reload
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
