#!/bin/bash

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_WEBDAV_CONFIGS=(
    "/etc/nginx/conf.d/openmediavault-lockzone.conf"
    "/etc/nginx/openmediavault-webgui.d/openmediavault-webdav.conf"
    "/etc/openmediavault-webdev.group.allow"
    "/etc/pam.d/openmediavault-webdav"
)

remove_action() {
    dpkg-trigger update-workbench

    # remove webdav nginx config files and reload nginx
    for conf in "${OMV_WEBDAV_CONFIGS[@]}"; do
        [ -e "${conf}" ] && rm -fv "${conf}"
    done
    deb-systemd-invoke reload nginx.service >/dev/null || true
}

case "$1" in
    purge)
        remove_action
        omv_config_delete "/config/services/webdav"
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
