#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in

    configure)

        if ! omv_config_exists "/config/services/webdav"; then
            echo "Initialize configuration"
            object="<enable>0</enable>"
            object="${object}<sharedfolderref></sharedfolderref>"
            omv_config_add_element "/config/services" "webdav" "${object}" true
        fi

        if ! grep -q "^webdavusers:" /etc/group; then
            echo "Add group: webdavusers"
            groupadd webdavusers
        else
            echo "webdavusers group already exists!"
        fi

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
