#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="webdav"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        # Add the default configuration
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "sharedfolderref"
            omv_config_add_element "${SERVICE_XPATH}" "upload_max" "2"
        fi

        # Add a webdav-users group.
        addgroup --quiet \
                 --system \
                 webdav-users

        # Add a webdav user.
        adduser --quiet \
                --system \
                --ingroup webdav-users \
                --no-create-home \
                --disabled-password \
                webdav

        # Make sure the webdav user can connect to engined.
        adduser --quiet \
                webdav openmediavault-engined

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
