#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
	purge)
		# Remove the configuration data
		omv_config_delete "/config/services/webdav"
	;;

	remove)

		if [ -h /etc/apache2/sites-enabled/omv-webdav ]
			then
				a2dissite "$WEBDAV_NAME" 2>&1
		fi
	
		if [ -h /etc/apache2/mods-enabled/dav_fs.load ]
			then
				a2dismod dav_fs 2>&1
				a2dismod dav 2>&1
		fi
	
		/etc/init.d/apache2 reload
	;;
	
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
	;;

	*)
		echo "postrm called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
